### ISSUE TITLE
Propose to combine all core Substeps into one repository

### ISSUE THREAD

**Issue by beercan1989** [G2G3Digital/substeps-core#24]
Due to dependencies on shared code between unreleased version it maybe a good idea to combine the core of Substeps into one git repository.

Don't think git sub-modules is adequate, as it will become a pain to handle pull requests on the individual repository when the builds only run on an 'uber' project.

One possible idea is to create a repository that looks like this, names of course are up for discussion as well as the solution:
* Substeps Core Parent
   * Substeps Api
   * Substeps Core
   * Substeps Runner
   * Substeps Glossary Builder

**Comment by iantmoore** [comment]
I think this is a good idea - independent chances to api and core are rare and frequently to enable changes in the runners.
I think the glossary builder should ultimately be merged into a single maven mojo with multiple goals.
As for the name - substeps-parent or substeps-core-parent ?

**Comment by beercan1989** [comment]
What happens to the glossary builder I think needs to be dealt with in a later task, its still going to be classified as core.

I would never have thought of looking to see if keeping a history in that manor was possible, good find.

**Comment by dowens-gd** [comment]
How about substeps-framework instead of substeps-parent?

**Comment by iantmoore** [comment]
yeah that's possibly better.

**Comment by dowens-gd** [comment]
https://github.com/G2G3Digital/substeps-framework is born
